### ISSUE TITLE
Crawler finds sitemap but does not find links in it

### ISSUE THREAD

**Issue by atn38** [algolia/algoliasearch-netlify#156]
Hello Algolia team,

I have a netlify website that is deployed using Netlify at https://ble.lternet.edu/, and would like to try Algolia for its search function. I made a fork of the underlying Github repository to test it out. The fork deploy URL is https://stoic-elion-ec8918.netlify.app/. 

I installed and made changes to the Algolia plugin config in netlify.toml according to your recommendations. The crawler seems to be able to find sitemap.xml, but no links within it (see screenshot). 

![image](https://user-images.githubusercontent.com/42045942/102415499-e3e90480-3fbd-11eb-9c44-f397dff965aa.png)

My hunch is that it's got something to do with the links in sitemap.xml being absolute URLs pointing to https://ble.lternet.edu/, and tried to set the customDomain parameter to match, but no dice. 

Any ideas? Thanks for your work!

**Comment by bodinsamuel** [comment]
Hello @atn38,

thanks for the very thorough report,
the domain must be set without the protocol, so just `ble.lternet.edu` 

I have tried and it seems to work better like this. 
I'll create a ticket on our side to improve the validation of this field 👍🏻 

Looking forward your answer

**Comment by atn38** [comment]
Hello @bodinsamuel,

Thanks for the hint -- this seems to work better. 
The crawler now finds most of the pages, except for one. Any ideas why this might happen?

**Comment by bodinsamuel** [comment]
> The crawler now finds most of the pages, except for one. Any ideas why this might happen?

Can you share which one? 
Usually that happens with orphan pages (not on sitemap or linked anywhere) but let's check

**Comment by atn38** [comment]
Turns out that was my bad, the page header canonical URL was wrong for that particular case. Thanks for your help!

**Comment by bodinsamuel** [comment]
Thanks for reaching out, very glad it's all good. 
Closing this issue 👍🏻
