### ISSUE TITLE
Search form doesn't work on a result page with hierarchical template

### ISSUE THREAD

**Issue by atn38** [algolia/algoliasearch-netlify#172]
Hello Algolia team,

I've run into another issue while testing Algolia on our website. https://stoic-elion-ec8918.netlify.app/index.html is the demo. I've set the search template in netlify.toml to "hierarchical" and added IDs to `<h1>` elements, so that when users click on a result the page jumps to that specific section. What I've noticed is that once the user is there, the search form doesn't work again. E.g. typing in queries does nothing. 

To replicate this behavior, you can try typing in "carbon" on the demo above, then go to the first result. From that page, type in carbon again and behold, nothing pops up.

Screenshots:

Searching from homepage:

![image](https://user-images.githubusercontent.com/42045942/103617777-74976e00-4ef4-11eb-99f7-51e4fe3bf103.png)

Searching from result page:

![image](https://user-images.githubusercontent.com/42045942/103617829-837e2080-4ef4-11eb-845a-4e6d59de8f2d.png)

From what I recall, this wasn't an issue when the indexing template was set to default.

**Comment by atn38** [comment]
Hello again,

To add to this, I think the issue lies with the ID part of the URL. What I mean is, with the hierarchical template, users are taken to URLs like https://stoic-elion-ec8918.netlify.app/people.html#tim. The search box doesn't work there, but it also doesn't work if I didn't go to the above URL by search but typed it in. I hope this helps.

**Comment by bodinsamuel** [comment]
Hello, sorry for the delay

Actually the search works but the overlay should be set in `position: fixed` because your header is following the scroll.
To do that you should add a css rule like this: 
```css
.aa-Panel {
position: fixed;
}
```

I wonder if it's possible to detect that automatically? cc @francoischalifour

**Comment by francoischalifour** [comment]
@bodinsamuel You mean having the `fixed` position hardcoded in the `style` in JavaScript instead of as part of the CSS? I think it makes sense—we'll make sure to address that when shipping the official theme in a few weeks.

**Comment by atn38** [comment]
Hi @bodinsamuel and @francoischalifour, thanks for detecting the problem. 

Yes, I think having this hardcoded would be good -- IMO a fixed header with a search box is a fairly common configuration for many people. In the meantime I'll follow your suggestion.

**Comment by bodinsamuel** [comment]
Closing as solved.
