### ISSUE TITLE
Crawler exclude pattern configuration

### ISSUE THREAD

**Issue by muenzpraeger** [algolia/algoliasearch-netlify#188]
Hello all!

Not sure if it's me configuring something wrong re: exclude patterns, or if I understood the documentation wrong.

I configured the `Allow` setting in [my robots.txt](https://muenzpraeger.netlify.app/robots.txt) to only crawl a specific section of test site. But still the crawler puts all sites in its index, like [this one](https://muenzpraeger.netlify.app/3/). Which then in return leads to weird search results, as the paginated pages are part of the search query.

From my understanding setting `Allow` is kind of a allowlist mechanism, and should be sufficient. Or is it that I have to set `Disallow` explicity, with an appropriate pattern?

Thanks!

**Comment by muenzpraeger** [comment]
Ok, after a couple of tries it seem that it's a denylist, and not an allowlist configuration.

After some going back and forth with configuration options I am not sure if the mechanism works as advertised.

For example, this setting `Disallow: /{1..9}` will still index pages that say i. e. `/3`.

**Comment by muenzpraeger** [comment]
Ok, after playing around more (and actually finding out that I mixed up `micromatch` and `robots.txt` syntax, sorry for that), I decided to _not_ use robots.txt, and instead use the `meta` directive as documented [here](https://github.com/algolia/algoliasearch-netlify/blob/master/docs/Extraction.md#using-meta-robots). This seems to be ignored.

As you can see on this screenshot the metatag is set for the page with the junction `/1/`.

![2021-01-26_08-17-06](https://user-images.githubusercontent.com/2205451/105812948-58489780-5faf-11eb-846d-faf0bebbda93.png)

But when I run the search the page still shows up in search results/is as indexed visible in the Crawler overview.

![2021-01-26_08-15-41](https://user-images.githubusercontent.com/2205451/105813035-7e6e3780-5faf-11eb-9028-2a4fb27b8674.png)

**Comment by bodinsamuel** [comment]
Hello,

> From my understanding setting Allow is kind of a allowlist mechanism, and should be sufficient. Or is it that I have to set Disallow explicity, with an appropriate pattern?

From the documentation Allow is `[...] used to override a Disallow directive to allow` so it works in combination with Disallow.
For example:
```txt
User-Agent: Algolia Crawler
Disallow: /*
Allow: /foobar
```

> For example, this setting Disallow: /{1..9} will still index pages that say i. e. /3.

Indeed robots.txt only support wildcard syntax, which has its own limitation.

> This seems to be ignored.

I will look into that, it should work. Thanks for the report.
Please note, it will block all robots to index this page (e.g: google bot too), 
that's why robots.txt is usually preferred as the syntax is made to adapt around user-agent.

**Comment by muenzpraeger** [comment]
I tried different variations for robots.txt, also like:

```
User-Agent: Algolia Crawler
Disallow: /*
Allow: /posts/*
```

Which results in a full block of all content.

![image](https://user-images.githubusercontent.com/2205451/105897854-0177a800-6019-11eb-948c-641e41c859a5.png)

**Comment by bodinsamuel** [comment]
Indeed, I was mistaken with the syntax, it's not possible to Disallow wildcard.
The Allow override only works with partial folder, like this:
```
User-Agent: Algolia Crawler
Disallow: /foo
Allow: /foo/index.html
```

NB: we are using https://www.npmjs.com/package/robots-parser

**Comment by bodinsamuel** [comment]
hey @muenzpraeger 
A fix has landed in production, can you try again with the noindex meta? 👍🏻

**Comment by muenzpraeger** [comment]
@bodinsamuel Thanks for putting in the fix - works like a charm!

**Comment by bodinsamuel** [comment]
Amazing news, thanks again for the report 🙏🏻

**Comment by bryanforbes** [comment]
Does excluding via the meta tag only work if the meta tag is exactly `<meta name="robots" content="noindex">`, or can we use `<meta name="Algolia Crawler" content="noindex">`? I want to exclude my landing page (`/`) from being indexed since it's just a list of recent blog posts, but since my posts are categorized by date (`/YYYY/MM/DD/post-slug/`), I don't want to do a `Disallow: /` and then an `Allow` for each year's posts since I'd have to remember to update my robots file every year.

**Comment by bodinsamuel** [comment]
Hello @bryanforbes 
We don't support the syntax `<meta name="Algolia Crawler" content="noindex">`, until now we have never seen anything else than the google version one so it was unnecessary but we could improve the support (same goes for `x-robots-tag` header)

I'll sync with the team and come back with an answer 👍🏻

**Comment by bryanforbes** [comment]
I did a little thinking and started generating my `robots.txt` with hugo to disallow the landing page and to allow all page directories, but the crawler now thinks there are no pages:

```
User-agent: Algolia Crawler
Disallow: /
Allow: /2011/
Allow: /2010/
Allow: /2009/
Allow: /2008/
Allow: /2007/
Allow: /2006/
Allow: /2005/
Allow: /2004/
```

Am I misunderstanding how the crawler works?

**Comment by bodinsamuel** [comment]
@bryanforbes
Here your are dissalowing the main page `/`, so that means we can not crawl it.
You need to do the opposite to achieve what you want

```
User-agent: Algolia Crawler
Disallow: /2011/
Disallow: /2010/
Disallow: /2009/
Disallow: /2008/
Disallow: /2007/
Disallow: /2006/
Disallow: /2005/
Disallow: /2004/
```

**Comment by bryanforbes** [comment]
@bodinsamuel I _want_ to disallow the main page and only allow my posts (I'm using this for a site search and I don't want the main page to be indexed since it's just summaries of the posts), so doing the opposite of what I had would only crawl non-posts.

**Comment by muenzpraeger** [comment]
I had the same. That's why I set `noindex` in the head, and didn't use the robots.

**Comment by bodinsamuel** [comment]
We have decided to move forward on the support `<meta name="Algolia Crawler" content="noindex">`
Creating a dedicated issue
