### ISSUE TITLE
Rendering issues on mobile

### ISSUE THREAD

**Issue by ketan-vijayvargiya** [algolia/algoliasearch-netlify#197]
Hi,

I integrated this plugin with my Netlify site last week. I am also using the `algoliasearch-netlify-frontend` bundle to render my search box.

The search box renders fine on the desktop version of the site but not on mobile. Please see the following screenshot from my phone.

![signal-2021-01-30-232021](https://user-images.githubusercontent.com/7019732/106377539-8680fb00-6352-11eb-83ab-0ee0c7575e8b.jpeg)

URL: ketanvijayvargiya.com/search/

(I would have liked to put the search box on the website header, so that it renders on every page, but my CSS-fu is so poor that I couldn't make that happen. So, for now, I am just putting a `<div id="search"/>` on a separate page.)

I am using Hugo as my SSG, in case that matters.

I'd appreciate it if someone can help me on this.

**Comment by sbellone** [comment]
Hi Ketan,
I can indeed reproduce this behaviour on Chrome. It works as expected on Firefox.
We will see what is going on and try to fix it. Thanks for reporting!

**Comment by ketan-vijayvargiya** [comment]
FYI: I am using Duckduckgo browser on iOS. But it could just be using Chromium underneath.

Thanks for the confirmation. Looking forward to the fix.

**Comment by sbellone** [comment]
Thanks for the information, it's indeed probably using Chromium underneath.

So we have identified the issue, the `autocomplete.js` team (the Algolia lib used in the packaged UI) has recently added Touch support (https://github.com/algolia/autocomplete.js/pull/379), and we had missed the fact that we had to update our CSS when we've updated the library.
You can expect the fix to be pushed early next week, sorry for that!

**Comment by sbellone** [comment]
Hi again Ketan, a version that fixes the issue and adds support for touch devices has been released. Let us know if you have any feedback!
