### ISSUE TITLE
front end module accessibility errors

### ISSUE THREAD

**Issue by atn38** [algolia/algoliasearch-netlify#203]
Hi folks, just FYI, when I run my website which has the Algolia front-end bundle through a web accessibility checker, it flags two things in the front end that I can't change but perhaps would be easy enough changes for you: 

1. The form with class "aa-Label" is empty
2. The button with class "aa-SubmitButton" is empty or has no value text

**Comment by bodinsamuel** [comment]
hey @atn38 thanks for the report.

Can you check @francoischalifour? ☺️

**Comment by francoischalifour** [comment]
Thanks @atn38—this is now fixed in the Autocomplete repo in [this commit](https://github.com/algolia/autocomplete/commit/45944e4c9f4e695039ab18e41284ff3d621774b7).

**Comment by atn38** [comment]
Hullo, @francoischalifour, pinging again since I don't think this is closed yet. Please see my previous comment.

**Comment by francoischalifour** [comment]
@atn38 The fix was released in Autocomplete v1.0.0-alpha.44, and the [Netlify plugin upgraded](https://github.com/algolia/algoliasearch-netlify/blob/d2c611827faad8c3ed3562c20835e9994f1bd26a/frontend/package.json#L21) to this version.

Are you still experiencing issues after upgrading?
