### ISSUE TITLE
`postinstall` script

### ISSUE THREAD

**Issue by ehmicky** [algolia/algoliasearch-netlify#23]
`tsc` is currently run on `postinstall`:

https://github.com/algolia/algoliasearch-netlify/blob/d545cc01244036007063abfe9f4efb7943f97af7/plugin/package.json#L17

However, it is also run before `yarn publish`:

https://github.com/algolia/algoliasearch-netlify/blob/d545cc01244036007063abfe9f4efb7943f97af7/plugin/package.json#L18

Should the `postinstall` script be removed?

**Comment by bodinsamuel** [comment]
Hey thanks for the feedback,
Mmh it's because on Netlify end's it will be installed with `npm install` and will trigger this?

**Comment by ehmicky** [comment]
Yes, it should be triggered by `npm install`. However, if TypeScript is already transpiled before `yarn publish`, then it should not be necessary to run it as a `postinstall` script? Please let me know if I am missing some information.

**Comment by Jerska** [comment]
This is WIP. The idea is to only run it if `dist` doesn't exist.
This is useful to deploy it as a local plugin of this repo (where `dist` is `.gitinore` d), but the published version (which users will install) should indeed skip this step.

**Comment by bodinsamuel** [comment]
Solved 👌🏻
