### ISSUE TITLE
Plugin name convention

### ISSUE THREAD

**Issue by ehmicky** [algolia/algoliasearch-netlify#24]
Plugin names follow a convention where they start with `netlify-plugin-` or `@scope/netlify-plugin-` ([link to documentation](https://docs.netlify.com/configure-builds/build-plugins/share-plugins/#publish-to-npm)).
This helps users discover and recognize Netlify plugins.

However, the plugin npm package is currently:

https://github.com/algolia/algoliasearch-netlify/blob/d545cc01244036007063abfe9f4efb7943f97af7/plugin/package.json#L2

**Comment by bodinsamuel** [comment]
arg, we should have checked before ahah 
We'll rename that 👍🏻
