### ISSUE TITLE
Debug statements

### ISSUE THREAD

**Issue by ehmicky** [algolia/algoliasearch-netlify#28]
This plugins prints the following values inside the build logs:

https://github.com/algolia/algoliasearch-netlify/blob/d545cc01244036007063abfe9f4efb7943f97af7/plugin/src/index.ts#L27-L29

Those values might be more useful for debugging, i.e. should they be printed?
Printing `process.env` might be a security concern as well since environment variables are likely to contain secret tokens, and build logs are often public.

**Comment by Jerska** [comment]
Yes they're meant to be commented out, but were useful to check out the differences between the builds on Netlify and the local builds using `yarn netlify build`.
