### ISSUE TITLE
`NODE_ENV=development` behavior

### ISSUE THREAD

**Issue by ehmicky** [algolia/algoliasearch-netlify#30]
When `NODE_ENV=development`: 
  - `siteName` is `crawler-netlify-plugin` 
  - `deployPrimeUrl` is `https://master--crawler-netlify-plugin.netlify.app`
  - the API key is `unused`

I wanted to confirm: is this temporary while this plugin is under development? The reason I am wondering is because some users have `NODE_ENV` set to `development` in their builds, so they would inherit this behavior, which might not be intended.

**Comment by bodinsamuel** [comment]
Ah we were not sure if env could conflict, we'll check that 👍🏻

**Comment by Jerska** [comment]
Definitely an env var we can replace with a custom one, e.g. `ALGOLIA_DEV_MODE=true`.
