### ISSUE TITLE
Inputs validation

### ISSUE THREAD

**Issue by ehmicky** [algolia/algoliasearch-netlify#31]
The `SITE_ID` constant and the `BRANCH` environment variables are always defined, including in CLI builds. Therefore, the following validation checks can probably be safely removed:

https://github.com/algolia/algoliasearch-netlify/blob/d545cc01244036007063abfe9f4efb7943f97af7/plugin/src/index.ts#L45-L46

Please note that the `SITE_NAME` environment variable is always defined in production builds, but not in CLI builds yet. However, this is a bug that is currently being fixed (see https://github.com/netlify/build/issues/1864).

https://github.com/algolia/algoliasearch-netlify/blob/d545cc01244036007063abfe9f4efb7943f97af7/plugin/src/index.ts#L48

**Comment by bodinsamuel** [comment]
Plugin is incompatible with local mode so not an issue. We'll block before that.
Thanks for the first suggestion 👌🏻
