### ISSUE TITLE
hierarchical search doesn't work

### ISSUE THREAD

**Issue by atn38** [algolia/algoliasearch-netlify#544]
Hello Algolia Netlify team,

I have an issue that's a bit inconsistent, i.e. it doesn't work but it doesn't not work all the time. Here goes: 

I have set the plugin "template" setting in the config .toml file to "hierarchical". Now, my understanding is that this tells Algolia to extract multiple records per page, one record per HTML header tag, and if these header tags contain an ID search results can display and jump to the specific header. I obtained a JSON export of the Algolia records that seems to confirm that at least the extraction part is working as expected. However, the actual search experience does not bear up to this. 

Here's my [main website](https://ble.lternet.edu/) and [github](https://github.com/BLE-LTER/LTER-website).

 Hierarchical search works for some pages, but not others. For example, it works for items in these pages [here ](https://ble.lternet.edu/student)and [here](https://ble.lternet.edu/research). Try searching for "Alina" or "Biological communities". But it doesn't work for headings in these pages [here](https://ble.lternet.edu/people) or [here](https://ble.lternet.edu/about). Try searching for "Dunton" or "policies". 

Note that the search result still returns the correct page, and also jumps to the correct header when selected, but does not display the heading. Search results also used to display the breadcrumbs trail "H1 heading > H2 heading > H3 heading" etc, but now no longer do, even for the pages that "work".

I'd appreciate insight as to why this is happening. Thanks a lot!

**Comment by bodinsamuel** [comment]
Hey @atn38 
thanks for the report, we are looking at it right now. I'll answer with more details 👍🏻

**Comment by bodinsamuel** [comment]
We have released a new version of the frontend to fix the display of headings in the autocomplete menu.

Your second issue seems to be related with your menu being `position: fixed`, not sure if it's an autocomplete.js issue (cc @francoischalifour). 
In the meantime you can fix it:
```css
.aa-Panel {
  top: 45px !important;
}
```

**Comment by atn38** [comment]
Hi @bodinsamuel, the fixes have worked great, thanks! The hierarchical search that wasn't working before is working now.

**Comment by bodinsamuel** [comment]
Thanks for confirming
