### ISSUE TITLE
Could not reach Algolia's Crawler, got: Internal Server Error {} ​

### ISSUE THREAD

**Issue by Deepanshu-dr** [algolia/algoliasearch-netlify#567]
I am facing this issue from past few builds.

Here is the deploy log

3:40:58 PM: Could not reach algolia Error: Internal Server Error {}
3:40:58 PM:     at onSuccess (/opt/build/repo/.netlify/plugins/node_modules/@algolia/netlify-plugin-crawler/dist/index.js:107:19)
3:40:58 PM:     at processTicksAndRejections (internal/process/task_queues.js:97:5)
3:40:58 PM:     at async Object.run (/opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/child/run.js:20:3)
3:40:58 PM:     at async handleEvent (/opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/child/main.js:36:38)
3:40:58 PM:     at async process.<anonymous> (/opt/buildhome/node-deps/node_modules/@netlify/build/src/plugins/ipc.js:103:16)
3:40:58 PM: ​
3:40:58 PM: ────────────────────────────────────────────────────────────────
3:40:58 PM:   Plugin "@algolia/netlify-plugin-crawler" failed               
3:40:58 PM: ────────────────────────────────────────────────────────────────
3:40:58 PM: ​
3:40:58 PM:   Error message
3:40:58 PM:   Error: Could not reach Algolia's Crawler, got: Internal Server Error {}
​
3:40:58 PM:   Plugin details
3:40:58 PM:   Package:        @algolia/netlify-plugin-crawler
3:40:58 PM:   Version:        1.0.0
3:40:58 PM:   Repository:     git+https://github.com/algolia/algoliasearch-netlify.git
3:40:58 PM:   npm link:       https://www.npmjs.com/package/@algolia/netlify-plugin-crawler
3:40:58 PM:   Report issues:  https://github.com/algolia/algoliasearch-netlify/issues
3:40:58 PM: ​
3:40:58 PM:   Error location
3:40:58 PM:   In "onSuccess" event in "@algolia/netlify-plugin-crawler" from Netlify app
3:40:58 PM:       at onSuccess (/.netlify/plugins/node_modules/@algolia/netlify-plugin-crawler/dist/index.js:112:21)
3:40:58 PM: ​
3:40:58 PM:   Resolved config
3:40:58 PM:   build:
3:40:58 PM:     base: /opt/build/repo
3:40:58 PM:     command: hugo --minify
3:40:58 PM:     commandOrigin: ui
3:40:58 PM:     environment:
3:40:58 PM:       - ALGOLIA_API_KEY
3:40:58 PM:       - ALGOLIA_BASE_URL
3:40:58 PM:     publish: /opt/build/repo/public
3:40:58 PM:     publishOrigin: ui
3:40:58 PM:   plugins:
3:40:58 PM:     - inputs: {}
3:40:58 PM:       origin: ui
3:40:58 PM:       package: '@algolia/netlify-plugin-crawler'
3:40:58 PM:

**Comment by sbellone** [comment]
Hi! Sorry for the troubles.
We indeed see some `401 Unauthorized` errors from Netlify for a siteId ending by `75d150`, is it yours?
If yes, we indeed don't handle automatic Netlify token refresh yet, could you try to logout and login again from the Algolia Crawler interface?
Let us know how it goes!
