### ISSUE TITLE
Add messages to the build logs

### ISSUE THREAD

**Issue by ehmicky** [algolia/algoliasearch-netlify#67]
The following lines are shown in the deploy summary:
  - Warning when `ALGOLIA_DISABLED` or `disabled` is used
  - Warning when the branch is not part of the `inputs.branches`
  - Success crawler URL

Would it be useful to print those in the build logs as well using `console.log()`? 

I was trying out the plugin myself and was wondering why the logs were only showing `Algolia Netlify plugin started`. After some time, I remembered that the deploy summary might have some information, and it did (I was on the wrong branch). In that case, seeing the information in the build logs might have helped. What do you think?

**Comment by bodinsamuel** [comment]
yes I agree
