### ISSUE TITLE
Incorrect error message when `ALGOLIA_BASE_URL` is missing

### ISSUE THREAD

**Issue by ehmicky** [algolia/algoliasearch-netlify#70]
When `ALGOLIA_BASE_URL` is missing, the following error message is printed:

```
Error: Missing ALGOLIA_BASE_URL, please go to undefined/admin/netlify to complete your installation.
```

This is because `algoliaBaseUrl` is `undefined` in:

https://github.com/algolia/algoliasearch-netlify/blob/09c288b76b57ef34eaa54ec74070b7c87d7913fe/plugin/src/index.ts#L94-L98

**Comment by bodinsamuel** [comment]
indeed, there was a default value before, small miss on our part there 👍🏻
