### ISSUE TITLE
Support for password protected website 

### ISSUE THREAD

**Issue by bodinsamuel** [algolia/algoliasearch-netlify#72]
Netlify have a way to protect website behind a password.
Algolia Crawler support authentication but it's not exposed in the plugin yet.

Should we support this?
If so, how?

**Comment by davatron5000** [comment]
👋  Hi, I use the Netlify Password Protection quite a bit, especially when I'm building out a sites before launch. It would be great to be able to validate Algolia works and is setup correctly before going LIVE.

I'd also love to index non-public app content behind Oauth or Netlify Identity logins as well. Thanks.

**Comment by bodinsamuel** [comment]
Password support has been deployed, if it's correctly configured in your Netlify account it should automatically works without any additional changes.
