### ISSUE TITLE
Migrate to autocomplete.js v1

### ISSUE THREAD

**Issue by bodinsamuel** [algolia/algoliasearch-netlify#76]
Currently we use the outdated autocomplete.js v0.
The decision was made for lack of better alternative and because we knew it correctly.
As the release of the refacto is coming soon and Docsearch using it, we could think about also migrating to v1.

**Comment by francoischalifour** [comment]
I'm heavily working on Autocomplete v1 so let's discuss this in the coming days. 🙂
