### ISSUE TITLE
Algolia Crawler did not populate an index

### ISSUE THREAD

**Issue by cindrmon1899** [algolia/algoliasearch-netlify#77]
Good day!

I tried installing the Algolia Plugin in netlify and I noticed that it didn't automatically populate an index.

When I tried entering the indices, it was blank, and prompted me to make a new index.

I am actually using Hugo for my blog website, and I wanted to add a search feature for it.

Is it because I am using Hugo that's why the plugin didn't work? 

Please help.

Thank you again for your time.

**Comment by bodinsamuel** [comment]
Hello @cindrmon1899,

Thanks for the report, can you provide the URL of your website and if possible the name of your Netlify website,
so that we can help you further in solving this issue.

In the meantime, we are aware of an issue with absolute canonical url making the crawl impossible:
see: https://github.com/algolia/algoliasearch-netlify/issues/73 
Might explain your issue.

Best Regards,

**Comment by bodinsamuel** [comment]
Did not receive additional info, feel free to reopen :)

**Comment by Pathsis** [comment]
> Did not receive additional info, feel free to reopen :)

I am experiencing the same problem. I am using [this theme](https://github.com/theNewDynamic/gohugo-theme-ananke). Algolia Crawler successfully crawls the urls, but the index has zero content.

My website address is *
Neflity's priamary address is *

Also, at the beginning this theme had built-in Robots.text that blocked the crawlers, I have removed it.

<img width="1473" alt="截屏2023-01-26 15 48 30" src="https://user-images.githubusercontent.com/72077265/214783191-21434981-8da9-4609-b7d4-06e885eb8077.png">

**Comment by sbellone** [comment]
Hi, your pages are asking robots to not index the content: `<meta name="robots" content="noindex, nofollow">`

**Comment by Pathsis** [comment]
> Hi, your pages are asking robots to not index the content: `<meta name="robots" content="noindex, nofollow">`

Thank you very, very much!
