### ISSUE TITLE
Algolia Netlify frontend script no-ops

### ISSUE THREAD

**Issue by kkgthb** [algolia/algoliasearch-netlify#82]
After configuring the Algolia Netlify Build Plugin and I embedded your script as suggested at https://github.com/algolia/algoliasearch-netlify/tree/master/frontend, but it doesn't do anything.  Here is the relevant HTML from my sample page:

```html


    <footer>
      <p>I'm a footer!  A copyright lives here, or something.</p>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@algolia/algoliasearch-netlify-frontend@0/dist/algoliasearchNetlify.css" />
      <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@algolia/algoliasearch-netlify-frontend@0/dist/algoliasearchNetlify.js"></script>
      <script type="text/javascript">
        algoliasearchNetlify({
          appId: 'ABC123',
          apiKey: '987654321',
          siteId: '123456789',
          branch: 'main',
          analytics: true,
          autocomplete: {
            hitsPerPage: 5,
            inputSelector: 'input[type=search]',
          },
          color: '#3c4fe0',
          debug: false,
          poweredBy: true,
        });
      </script>
    </footer>
```

I wasn't sure if I was just missing a manual input box, but that didn't help either.

```html
    <footer>
      <p>I'm a footer!  A copyright lives here, or something.</p>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@algolia/algoliasearch-netlify-frontend@0/dist/algoliasearchNetlify.css" />
      <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@algolia/algoliasearch-netlify-frontend@0/dist/algoliasearchNetlify.js"></script>
      <script type="text/javascript">
        algoliasearchNetlify({
          appId: 'ABC123',
          apiKey: '987654321',
          siteId: '123456789',
          branch: 'main',
          analytics: true,
          autocomplete: {
            hitsPerPage: 5,
            inputSelector: 'input[type=search]',
          },
          color: '#3c4fe0',
          debug: false,
          poweredBy: true,
        });
      </script>
      <label for="site-search">Search the site:</label>
      <input type="search" id="site-search" name="q" aria-label="Search through site content">
      <button>Search</button>
	  <p>End of footer</p>
    </footer>
```

Is there something broken, did I misunderstand your getting started directions, is there a typo in the directions, etc?

Note that my Netlify build DID index my site -- I can see content from my site at https://www.algolia.com/apps/ABC123/explorer/browse/netlify_123456789_main_all

**Comment by Jerska** [comment]
Hi there! First, thanks for reporting the issue. :)

You are correct, having an input matching `autocomplete.inputSelector` in your DOM is necessary.
We should definitely add a warning when we can't find such an input.

The library should wait for `DOMContentLoaded` to trigger the render call which looks for inputs.
However, if you're adding this code dynamically, this could explain the issue.
Can you try moving the `<script>` tag invoking the library **after** your `<input />` tag?

If this doesn't solve the issue, could you share a reproduction setup with us?
If you're worried about sharing your website publicly, you can reach out to support@algolia.com referencing this issue.

Also, note that the input is designed to be located at the top or center of the page (with the results below the search input).
I'm really not sure it will display correctly in a footer.

**Comment by bodinsamuel** [comment]
Did not receive additional comments, feel free to reopen :)
