### ISSUE TITLE
After build triggers plugin can algolia search another Netlify url - not the repo that triggers it?

### ISSUE THREAD

**Issue by tyeeman** [algolia/algoliasearch-netlify#847]
I have my code in a Github repo, my other files (pdfs, html, images, etc.) are in another Netlify domain for storage. When I update my repo I want algolia to scan this other Netlify domain for changes (There will be changes that I have done manually). Is this possible? If not how am I supposed to store all these files (not on Github) but be able to have an algolia search on them?

**Comment by sbellone** [comment]
No, the plugin only crawls the site linked to the repo.
You can ask Netlify about your setup, but the plugin won't crawl PDFs or images anyway.
