### ISSUE TITLE
Nothing is showed in front-end

### ISSUE THREAD

**Issue by xplosionmind** [algolia/algoliasearch-netlify#99]
Hello, I have an issue similar to #82. The following is my code, which appears as grey (unactive) in my developer tools, and I can't figure out why.

![Dev tools screenshot](https://user-images.githubusercontent.com/42862428/97114411-a0c29180-16f0-11eb-9544-23d0826d9f8e.jpg)

This is my code:
```
<div id="search" class="row">
	<script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@algolia/algoliasearch-netlify-frontend@0/dist/algoliasearchNetlify.js"></script>
	<script type="text/javascript">
		algoliasearchNetlify({
			appId: 'UNJ7U6R9NG',
			apiKey: '2496a32ec63dd08b35a3************',
			siteId: 'c7f3a969-424a-450b-8636-2d477af82e76',
			branch: 'master',
		});
	</script>
</div>
```

I censored the last part of my API key but, if necessary, I can share it. I have no experience with JavaScript or APIs at all, I really need some help, here.

Note: there's no CSS since I embedded it in my website's CSS file to improve performance.

Thanks in advance!

Best,

Tommi

**Comment by Jerska** [comment]
Hi there!

> I censored the last part of my API key but, if necessary, I can share it.

In this case it's not necessary, but don't worry about sharing it.
As it lives in your website's front-end code, it is anyway accessible by any website user and must be considered public.
All it can be used for is to run search queries against the index we've built.

> Note: there's no CSS since I embedded it in my website's CSS file to improve performance.

Definitely a good idea!

---

> I have an issue similar to #82. The following is my code, which appears as grey (unactive) in my developer tools, and I can't figure out why.

Your problem does indeed sound similar to the one in #82 .

The integration does not add a search input to your website, it only enhances an already existing one.
Do you have, anywhere in your page, a search input like so?

```html
  <input type="search" placholder="Search on this website..." />
```

The CSS selector we use by default is `input[type=search]`.
You can customize it with the  `autocomplete.inputSelector` option if necessary.

**Comment by xplosionmind** [comment]
Thanks a lot, @Jerska. Solved! It was this:

> The integration does not add a search input to your website, it only enhances an already existing one.
> Do you have, anywhere in your page, a search input like so?
> 
> ```
>   <input type="search" placholder="Search on this website..." />
> ```

Stupidly, I thought the script would create a search input, too.



Now, can I quickly ask you off-topic how to increase the number of preview lines for matching words? Like this it's useless…

![Screenshot 2020-10-27 at 10 42 02 AM](https://user-images.githubusercontent.com/42862428/97284232-163d7780-1841-11eb-80fe-1f1fcbb9fa05.jpg)

**Comment by Jerska** [comment]
> Now, can I quickly ask you off-topic how to increase the number of preview lines for matching words? Like this it's useless…

Indeed, this is useless. 😅 
The amount of words is the snippet is computed based on the input width.
It looks like the snipppeting function computed 0 words to display (our snippeting always returns at least one word):

https://github.com/algolia/algoliasearch-netlify/blob/dbfce6fdeda9a96826540c81510d93d7e25733fe/frontend/src/AutocompleteWrapper.ts#L147-L151

The only scenario in which this should happen is when the input is less than 400px large, which doesn't appear to be the case.
Also, in the case, the input should not display the description:

https://github.com/algolia/algoliasearch-netlify/blob/dbfce6fdeda9a96826540c81510d93d7e25733fe/frontend/src/index.scss#L119-L121

Do you have a live version of the website I could try to reproduce this on?

**Comment by xplosionmind** [comment]
> It looks like the snipppeting function computed 0 words to display (our snippeting always returns at least one word):

why is this happening? What could I do to fix it?



> Also, in the case, the input should not display the description:
> 
> https://github.com/algolia/algoliasearch-netlify/blob/dbfce6fdeda9a96826540c81510d93d7e25733fe/frontend/src/index.scss#L119-L121

I changed the display option: if I kept this disabled, it would show only the title of the article.



> Do you have a live version of the website I could try to reproduce this on?

Thanks, you're very kind. Of course! [This](https://github.com/xplosionmind/tommi.space) is the repo with the website source code and [here](https://tommi.space) is my website up and running.

**Comment by sbellone** [comment]
Hi @xplosionmind, sorry for the late answer!
Thanks for providing your website link. This is happening because we calculate the number of snippet words when the plugin is loaded. And at that time, your search input's width is only `3.1 rem` (just the button's width).

If you want to use our frontend bundle as-is, you'll have to use another technique: either having the search input already present on the page in full width but not displayed and making appearing when we hover the button, or instantiate the algoliasearchNetlify on the first hover.

Let us know if you manage to do it!

**Comment by Jerska** [comment]
Oh, my apologies for missing your answer @xplosionmind! Thanks @sbellone for taking over.

**Comment by xplosionmind** [comment]
Thanks a lot! I'll look at it. (Sorry for my late reply, too).

**Comment by sbellone** [comment]
No problem :)
Note that since then we've released a v1 of the UI, which has slightly different behaviour (and which is meant to be injected in a `<div>` and not in an `<input>` anymore). Keep us posted!
